name = "ant-colony"
compatibility_date = "2024-05-16"
compatibility_flags = ["nodejs_compat"]

# Cloudflare Pages Functions 配置
# 环境变量需在 Cloudflare Pages 后台设置，不要写在这里

[build]
command = ""
pages_build_output_dir = "./"